AllCops:
  Exclude:
    - "db/**/*"
    - "bin/*" 
    - "config/**/*"
    - "Guardfile"
    - "Rakefile"
    - "README.md"
    - "node_modules/**/*"

  DisplayCopNames: true

Layout/LineLength:
  Enabled: true
  Max: 120
Metrics/MethodLength:
  Enabled: true
  Include:
    - "app/controllers/*"
    - "app/models/*"
  Max: 20
Metrics/AbcSize:
  Enabled: true
  Include:
    - "app/controllers/*"
    - "app/models/*"
  Max: 50
Metrics/ClassLength:
  Enabled: true
  Max: 150
Metrics/BlockLength:
  Enabled: true
  ExcludedMethods: ['describe']
  Max: 30

Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/EachForSimpleLoop:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/DefWithParentheses:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: never

Layout/HashAlignment:
  Enabled: true
  EnforcedColonStyle: key
Layout/ExtraSpacing:
  Enabled: true
  AllowForAlignment: false
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented